MODE: 1             
MODEL: 1            
SEED: 10            
GPU: [0]            
DEBUG: 0            
VERBOSE: 0          
TEST_MODE: hazy     

TRAIN_CLEAN_FLIST: ./datasets/
TRAIN_HAZY_FLIST: ./datasets/
TEST_HAZY_FLIST: ./datasets/
DATASET:  ITS         


LR: 0.0001                       
WEIGHT_DECAY: 0                   
D2G_LR: 0.1                   
BETA1: 0.9                    
BETA2: 0.999                   
BATCH_SIZE: 2                 
CROP_SIZE: 256               
MAX_ITERS: 1000000                
BASE_CHANNEL_NUM: 64



MIN_BETA: 0.5
MAX_BETA: 1.5
MIN_D: 0.1                    
MAX_D: 5


USE_DC_A:                     
USE_GUIDED_FILTER:            


CONTRAST_LOSS_WEIGHT: 0.0001
GAN_LOSS_WEIGHT: 0.1
CYCLE_LOSS_WEIGHT: 1 
PARA_LOSS_WEIGHT: 1


GAN_LOSS: lsgan               
GAN_POOL_SIZE: 0              

SAVE_INTERVAL: 2000           
SAMPLE_INTERVAL: 2000       
SAMPLE_SIZE: 4               
EVAL_INTERVAL: 1000              
LOG_INTERVAL: 100              
